#! /usr/bin/env bash
set -euo pipefail

base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"

bosh -e prod deploy -d nexus \
  -l "${base}/bosh-secrets/vars-nexus.yml" \
  -l "${repo}/deployments/nexus/versions.yml" \
  "${repo}/deployments/nexus/nexus.yml" \
  "$@"

echo "Finished deploying: nexus"
