---
name: nexus

releases:
- name: nexus
  version: ((nexus_version))
  url: https://github.com/making/nexus-boshrelease/releases/download/((nexus_version))/nexus-boshrelease-((nexus_version)).tgz
  sha1: ((nexus_sha1))
- name: openjdk
  version: ((openjdk_version))
  url: https://github.com/making/openjdk-boshrelease/releases/download/((openjdk_version))/openjdk-boshrelease-((openjdk_version)).tgz
  sha1: ((openjdk_sha1))

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nexus
  instances: 1
  vm_type: micro
  persistent_disk_type: 20480
  stemcell: default
  azs: [z1]
  networks:
  - name: default
    static_ips:
    - ((nexus_web_ip))
  jobs:
  - name: java
    release: openjdk
  - name: nexus
    release: nexus
    properties:
      nexus:
        heap_size: 768M
        max_direct_memory_size: 512M
        admin_password: ((admin_password))
  - name: nexus-backup
    release: nexus

variables:
- name: admin_password
  type: password

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
