---
name: nexus

releases:
- name: nexus
  version: 0.14.1
  url: https://github.com/making/nexus-boshrelease/releases/download/0.14.1/nexus-boshrelease-0.14.1.tgz
  sha1: 8c3ca35c5da68c37109ffda0c7365ef7ca639978
- name: openjdk
  version: 8.0.4
  url: https://github.com/making/openjdk-boshrelease/releases/download/8.0.4/openjdk-boshrelease-8.0.4.tgz
  sha1: 43979a6595282fcf4ac6269135968acc0d96d297

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nexus
  instances: 1
  vm_type: micro
  persistent_disk_type: 20480
  stemcell: default
  azs: [z1]
  networks:
  - name: default
#    static_ips: [((internal_ip))]
  jobs:
  - name: java
    release: openjdk
  - name: nexus
    release: nexus
    properties:
      nexus:
        heap_size: 768M
        max_direct_memory_size: 512M
        admin_password: ((admin_password))
  - name: nexus-backup
    release: nexus

variables:
- name: admin_password
  type: password

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
