---
name: nexus

releases:
- name: nexus
  version: 0.13.0
  url: https://github.com/making/nexus-boshrelease/releases/download/0.13.0/nexus-boshrelease-0.13.0.tgz
  sha1: 9e7b17302e56bf360bf56b627d37fe902ed49e1b
- name: openjdk
  version: 8.0.2
  url: https://github.com/making/openjdk-boshrelease/releases/download/8.0.2/openjdk-boshrelease-8.0.2.tgz
  sha1: e76b73d2560d143b155e958aa06a2e266e261464

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nexus
  instances: 1
  vm_type: micro
  persistent_disk_type: 20480
  stemcell: default
  azs: [z1]
  networks:
  - name: default
#    static_ips: [((internal_ip))]
  jobs:
  - name: java
    release: openjdk
  - name: nexus
    release: nexus
    properties:
      nexus:
        heap_size: 768M
        max_direct_memory_size: 512M
        admin_password: ((admin_password))
  - name: nexus-backup
    release: nexus

variables:
- name: admin_password
  type: password

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
