---
name: nexus

releases:
- name: nexus
  version: 0.12.1
  url: https://github.com/making/nexus-boshrelease/releases/download/0.12.1/nexus-boshrelease-0.12.1.tgz
  sha1: 42fd399f34a4ed116455147e78fdaf6c8b7f8148
- name: openjdk
  version: 8.0.1
  url: https://github.com/making/openjdk-boshrelease/releases/download/8.0.1/openjdk-boshrelease-8.0.1.tgz
  sha1: d02566fb6d974de4b60bf44dc21e56422c7da3fd

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

instance_groups:
- name: nexus
  instances: 1
  vm_type: micro
  persistent_disk_type: 20480
  stemcell: default
  azs: [z1]
  networks:
  - name: default
#    static_ips: [((internal_ip))]
  jobs:
  - name: java
    release: openjdk
  - name: nexus
    release: nexus
    properties:
      nexus:
        heap_size: 768M
        max_direct_memory_size: 512M
  - name: nexus-backup
    release: nexus

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
