---
name: nexus

releases:
- name: nexus
  version: 0.10.1
  url: https://github.com/making/nexus-boshrelease/releases/download/0.10.1/nexus-boshrelease-0.10.1.tgz
  sha1: 2ebba1689013a9cdbbe12c3fca76f5b1b82564aa

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3586.latest

instance_groups:
- name: nexus
  instances: 1
  vm_type: micro
  persistent_disk_type: 20480
  stemcell: default
  azs: [z1]
  networks:
  - name: default
#    static_ips: [((internal_ip))]
  jobs:
  - name: nexus
    release: nexus
    properties:
      nexus:
        heap_size: 768M
        max_direct_memory_size: 512M
  - name: nexus-backup
    release: nexus

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
