---
jobs:
- name: scale-apps
  plan:
  - put: nulldriver
    params:
      commands:
      - command: scale
        space: notifications-with-ui
        app_name: notifications
        instances: 1
      - command: scale
        space: notifications-with-ui
        app_name: notifications-ui
        instances: 1
      - command: scale
        space: system
        app_name: app-usage-scheduler
        instances: 1
        memory: 256MB
      - command: scale
        space: system
        app_name: app-usage-server
        instances: 1
        memory: 512MB
      - command: scale
        space: system
        app_name: app-usage-worker
        instances: 1
        memory: 512MB
      - command: scale
        space: system
        app_name: apps-manager-js-green
        instances: 1
      - command: scale
        space: system
        app_name: p-invitations-green
        instances: 1
      - command: scale
        space: system
        app_name: search-server-green
        instances: 1

resources:
- name: nulldriver
  type: cf-cli-resource
  source:
    api: https://api.run.nulldriver.com
    username: ((cf.username))
    password: ((cf.password))
    org: system

resource_types:
- name: cf-cli-resource
  type: registry-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest
