#! /usr/bin/env bash
set -euo pipefail

base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../../.." && pwd )"
repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"

# Deploy minio
bosh -e prod deploy -d minio \
  --vars-file "${base}/bosh-secrets/vars-minio.yml" \
  --vars-file "${repo}/deployments/minio/versions.yml" \
  "${repo}/deployments/minio/minio.yml" \
  "$@"

echo "Finished deploying: minio"
