---
name: minio

releases:
- name: "minio"
  version: "2019-10-12T01-39-57Z"
  url: "https://bosh.io/d/github.com/minio/minio-boshrelease?v=2019-10-12T01-39-57Z"
  sha1: "91fa5e22e9aaaebe9f86e4a08f252c33eac6bbb9"

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

variables:
- name: minio_accesskey
  type: password
- name: minio_secretkey
  type: password

instance_groups:
- name: minio
  azs: [z1]
  instances: 1
  jobs:
  - name: minio-server
    release: minio
    templates:
    - name: minio-server
    provides:
      minio-server: {as: minio-link}
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      port: 9000
  networks:
  - name: default
    static_ips:
    - ((web_ip))
  vm_type: micro
  persistent_disk_type: 51200
  stemcell: default

- name: tests
  azs: [z1]
  instances: 1
  lifecycle: errand
  post_deploy: true
  jobs:
  - name: smoke-tests
    release: minio
    templates:
    - name: smoke-tests
    consumes:
      minio: {from: minio-link}
  networks:
  - name: default
  vm_type: micro
  persistent_disk_type: 2048
  stemcell: default

- name: bucket-seeding # To create default buckets after manifest-deploy
  azs: [z1]
  instances: 1
  lifecycle: errand
  post_deploy: true
  jobs:
  - name: mc
    release: minio
    templates:
    - name: mc
    consumes:
      minio: {from: minio-link}
    properties:
      script: |
        #!/bin/sh
        mc mb myminio/pcf-backups
        mc mb myminio/pcf-bosh
        mc mb myminio/pcf-buildpacks
        mc mb myminio/pcf-droplets
        mc mb myminio/pcf-packages
        mc mb myminio/pcf-resources
  networks:
  - name: default
  vm_type: micro
  persistent_disk_type: 2048
  stemcell: default

update:
  canaries: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  max_in_flight: 1
