# Variables:
#   vcenter_cluster
#   network_name
#   internal_gw
#   internal_cidr
#   internal_static_ips
---
azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [((vcenter_cluster)): {}]

networks:
- name: default
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: ((network_name))
    dns: ((internal_dns))
    gateway: ((internal_gw))
    range: ((internal_cidr))
    reserved: []
    static: ((static_ips))
  type: manual
- name: cf-deployment
  subnets:
  - azs:
    - z1
    cloud_properties:
      name: ((cf_deployment_network_name))
    dns: ((cf_deployment_internal_dns))
    gateway: ((cf_deployment_internal_gw))
    range: ((cf_deployment_internal_cidr))
    reserved: []
    static: ((cf_deployment_static_ips))
  type: manual

disk_types:
- name: 5GB
  disk_size: 5120
  cloud_properties:
    type: thin
- name: 10GB
  disk_size: 10240
  cloud_properties:
    type: thin
- name: 20GB
  disk_size: 20480
  cloud_properties:
    type: thin
- name: 50GB
  disk_size: 51200
  cloud_properties:
    type: thin
- name: 100GB
  disk_size: 102400
  cloud_properties:
    type: thin

vm_types:
- name: bosh.worker
  cloud_properties:
    cpu: 4
    ram: 4096
    disk: 16384
- name: caddy.server
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 8192

- name: minimal
  cloud_properties:
    cpu: 1
    ram: 4096
    disk: 10240
- name: small
  cloud_properties:
    cpu: 2
    ram: 8192
    disk: 10240
- name: small-highmem
  cloud_properties:
    cpu: 4
    ram: 32768
    disk: 10240

- name: cf.api
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.cc-worker
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.credhub
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.database
  cloud_properties:
    cpu: 2
    ram: 8192
    disk: 10240
- name: cf.diego-api
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.diego-cell
  cloud_properties:
    cpu: 4
    ram: 32768
    disk: 10240
- name: cf.doppler
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.log-api
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.log-cache
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.nats
  cloud_properties:
    cpu: 1
    ram: 8192
    disk: 30720
- name: cf.rotate-cc-database-key
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.router
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.scheduler
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.smoke-tests
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: cf.uaa
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192

- name: concourse.web
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: concourse.db
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: concourse.worker
  cloud_properties:
    cpu: 4
    ram: 4096
    disk: 65536
- name: minio.server
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: nexus.server
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: postgres.server
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: pxc.server
  cloud_properties:
    cpu: 1
    ram: 2048
    disk: 16384

vm_extensions:
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
- name: diego-ssh-proxy-network-properties
- name: 50GB_ephemeral_disk
  cloud_properties:
    disk: 51200
- name: 100GB_ephemeral_disk
  cloud_properties:
    disk: 102400

compilation:
  workers: 4
  reuse_compilation_vms: true
  az: z1
  vm_type: bosh.worker
  network: default
