#! /usr/bin/env bash
set -eu
set -o pipefail

# To generate a manifest with variable interpolation placeholders intact,
# suitable to be committed to source control

function get_yaml_value() {
  local key=${1:?key null or not set}
  local file=${2:?file null or not set}

  if ! yq_cli=$(command -v yq); then
    echo "unable to locate yq binary (https://github.com/mikefarah/yq)" >&2
    exit 1
  fi

  if [[ "$(yq --version)" != *"version v4"* ]]; then
    echo "yq v4 is required (found $(yq --version))" >&2
    exit 12
  fi

  "$yq_cli" "$key" "$file"
}

base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"

# make sure we have concourse-bosh-deployment
if [[ ! -d "${repo}/tmp/concourse-bosh-deployment" ]] ; then
  pushd ${repo}/tmp > /dev/null
    git clone https://github.com/concourse/concourse-bosh-deployment.git &> /dev/null
  popd > /dev/null
fi

# checkout specific version of concourse-bosh-deployment
REF="v$(get_yaml_value '.concourse_version' "${repo}/deployments/concourse/versions.yml")"
echo "Checking out to concourse-bosh-deployment to ref: ${REF}"

pushd ${repo}/tmp/concourse-bosh-deployment > /dev/null
  git fetch &> /dev/null
  git checkout ${REF} &> /dev/null
  git log -1 --pretty=oneline
popd > /dev/null

# Generated manifest
manifest="${repo}/deployments/concourse/concourse.yml"

bosh interpolate "${repo}/tmp/concourse-bosh-deployment/cluster/concourse.yml" \
  -l "${repo}/deployments/concourse/versions.yml" \
  -l "${repo}/tmp/concourse-bosh-deployment/versions.yml" \
  -o "${repo}/tmp/concourse-bosh-deployment/cluster/operations/basic-auth.yml" \
  -o "${repo}/tmp/concourse-bosh-deployment/cluster/operations/static-web.yml" \
  -o "${repo}/tmp/concourse-bosh-deployment/cluster/operations/scale.yml" \
  -o "${repo}/tmp/concourse-bosh-deployment/cluster/operations/garden-dns.yml" \
  -o "${repo}/tmp/concourse-bosh-deployment/cluster/operations/github-auth.yml" \
  -o "${repo}/tmp/concourse-bosh-deployment/cluster/operations/credhub.yml" \
  -o "${repo}/tmp/concourse-bosh-deployment/cluster/operations/x-frame-options-sameorigin.yml" \
  -o "${repo}/deployments/concourse/operations.yml" \
   > "${manifest}"

echo -e "# Generated file - do not edit directly!\n---\n$(cat $manifest)" > "$manifest"
echo "Generating manifest: $manifest"

bosh deploy -d concourse \
  -l "${base}/bosh-secrets/vars-concourse.yml" \
  -l "${base}/bosh-secrets/vars-static-ips.yml" \
  "${manifest}" \
  "$@"

echo "Finished deploying: concourse"
