#! /usr/bin/env bash
set -eu
set -o pipefail

# To generate a manifest with variable interpolation placeholders intact,
# suitable to be committed to source control

function get_yaml_value() {
  local key=${1:?key null or not set}
  local file=${2:?file null or not set}

  if ! yq_cli=$(command -v yq); then
    echo "unable to locate yq binary (https://github.com/mikefarah/yq)" >&2
    exit 1
  fi

  if [[ "$(yq --version)" != *"version v4"* ]]; then
    echo "yq v4 is required (found $(yq --version))" >&2
    exit 12
  fi

  "$yq_cli" "$key" "$file"
}

base="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../.." && pwd )"
repo="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd )"

# make sure we have cf-deployment
if [[ ! -d "${repo}/tmp/cf-deployment" ]] ; then
  pushd ${repo}/tmp > /dev/null
    git clone https://github.com/cloudfoundry/cf-deployment.git &> /dev/null
  popd > /dev/null
fi

# checkout specific version of cf-deployment
REF="v$(get_yaml_value '.cf_version' "${repo}/deployments/cf/versions.yml")"
echo "Checking out to cf-deployment to ref: ${REF}"

pushd ${repo}/tmp/cf-deployment > /dev/null
  git fetch &> /dev/null
  git checkout ${REF} &> /dev/null
  git log -1 --pretty=oneline
popd > /dev/null

# Generated manifest
manifest="${repo}/deployments/cf/cf.yml"

bosh interpolate "${repo}/tmp/cf-deployment/cf-deployment.yml" \
  -o "${repo}/tmp/cf-deployment/operations/rename-network-and-deployment.yml" \
  -o "${repo}/tmp/cf-deployment/operations/scale-to-one-az.yml" \
  -o "${repo}/tmp/cf-deployment/operations/set-router-static-ips.yml" \
  -o "${repo}/tmp/cf-deployment/operations/stop-skipping-tls-validation.yml" \
  -o "${repo}/tmp/cf-deployment/operations/override-app-domains.yml" \
  -o "${repo}/tmp/cf-deployment/operations/enable-v2-api.yml" \
  -o "${repo}/deployments/cf/operations.yml" \
   > "${manifest}"

echo -e "# Generated file - do not edit directly!\n---\n$(cat $manifest)" > "$manifest"
echo "Generating manifest: $manifest"

bosh -d cf deploy \
  -l "${base}/bosh-secrets/vars-cf.yml" \
  -l "${base}/bosh-secrets/vars-static-ips.yml" \
  "${manifest}" \
  "$@"

echo "Finished deploying: cf"
